/**
 * llms.txt Format Specification
 *
 * Defines the canonical format for llms.txt files generated by this service.
 * Based on: https://llmstxt.org/
 *
 * This serves as:
 * - Single source of truth for format validation
 * - Documentation for the expected structure
 * - Schema for testing and quality gates
 */

export interface LlmsTxtSpec {
  /** Must start with a top-level heading */
  hasTitle: boolean;

  /** Must have at least one section */
  hasSections: boolean;

  /** Must contain links */
  hasLinks: boolean;

  /** Must be multi-line (not empty) */
  isMultiLine: boolean;

  /** Must contain HTTP(S) URLs */
  hasUrls: boolean;
}

/**
 * llms.txt Format Requirements
 *
 * Based on https://llmstxt.org/ specification:
 *
 * ```markdown
 * # Site Name
 *
 * Brief description of the site
 *
 * ## Section Name
 *
 * - [Link Text](https://example.com/path): Description
 * - [Another Link](https://example.com/other): Description
 *
 * ## Another Section
 *
 * Content...
 * ```
 */
export const LLMS_TXT_REQUIREMENTS = {
  /** Must start with exactly one top-level heading (# ) */
  titlePattern: /^# .+$/m,

  /** Must have at least one section heading (## ) */
  sectionPattern: /^## .+$/m,

  /** Must contain markdown links [text](url) */
  linkPattern: /\[.+?\]\(https?:\/\/.+?\)/,

  /** Must contain URLs */
  urlPattern: /https?:\/\/[^\s]+/,

  /** Minimum line count (prevents empty/trivial output) */
  minLines: 5,

  /** Recommended maximum line count (prevents bloat) */
  maxLines: 10000,
} as const;

/**
 * Validate llms.txt format
 *
 * @param content - Generated llms.txt content
 * @returns Validation result with specific failures
 */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  stats: {
    lineCount: number;
    sectionCount: number;
    linkCount: number;
    urlCount: number;
  };
}

export function validateLlmsTxtFormat(content: string): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Basic structure checks
  const lines = content.split("\n");
  const lineCount = lines.length;

  if (lineCount < LLMS_TXT_REQUIREMENTS.minLines) {
    errors.push(
      `Content too short (${lineCount} lines, minimum ${LLMS_TXT_REQUIREMENTS.minLines})`
    );
  }

  if (lineCount > LLMS_TXT_REQUIREMENTS.maxLines) {
    warnings.push(
      `Content very long (${lineCount} lines, recommended max ${LLMS_TXT_REQUIREMENTS.maxLines})`
    );
  }

  // Title check
  if (!LLMS_TXT_REQUIREMENTS.titlePattern.test(content)) {
    errors.push("Missing top-level heading (# Title)");
  }

  // Section check
  const sectionMatches = content.match(/^## .+$/gm);
  const sectionCount = sectionMatches?.length || 0;

  if (sectionCount === 0) {
    errors.push("No sections found (## Section Name)");
  }

  if (sectionCount < 2) {
    warnings.push(`Only ${sectionCount} section found, expected 2+`);
  }

  // Link check
  const linkMatches = content.match(/\[.+?\]\(https?:\/\/.+?\)/g);
  const linkCount = linkMatches?.length || 0;

  if (linkCount === 0) {
    errors.push("No links found ([text](url))");
  }

  if (linkCount < 5) {
    warnings.push(`Only ${linkCount} links found, expected 5+`);
  }

  // URL check
  const urlMatches = content.match(/https?:\/\/[^\s)]+/g);
  const urlCount = urlMatches?.length || 0;

  if (urlCount === 0) {
    errors.push("No URLs found");
  }

  // Empty sections check
  const emptySections = content.match(/^## .+$\s*^##/gm);
  if (emptySections && emptySections.length > 0) {
    warnings.push(`${emptySections.length} empty sections found`);
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
    stats: {
      lineCount,
      sectionCount,
      linkCount,
      urlCount,
    },
  };
}

/**
 * Quick validation for tests - throws on invalid format
 */
export function assertValidLlmsTxt(content: string): void {
  const result = validateLlmsTxtFormat(content);

  if (!result.valid) {
    throw new Error(
      `Invalid llms.txt format:\n${result.errors.map((e) => `  - ${e}`).join("\n")}`
    );
  }
}

/**
 * Example valid llms.txt for tests
 */
export const EXAMPLE_LLMS_TXT = `# Example Site

A brief description of what this site offers.

## Getting Started

- [Introduction](https://example.com/intro): Getting started guide
- [Quick Start](https://example.com/quick-start): 5-minute tutorial

## Documentation

- [API Reference](https://example.com/api): Complete API documentation
- [Guides](https://example.com/guides): Step-by-step tutorials

## Community

- [GitHub](https://github.com/example): Source code and issues
- [Discord](https://discord.gg/example): Community chat
`;
